In [9]:
from analiseExploratoria import *
pd.set_option('display.max_columns', None)

In [10]:
dados = carregar_dados("./heart_attack_prediction_dataset.csv")
dados.head()

,Patient ID,Age,Sex,Cholesterol,Blood Pressure,Heart Rate,Diabetes,Family History,Smoking,Obesity,Alcohol Consumption,Exercise Hours Per Week,Diet,Previous Heart Problems,Medication Use,Stress Level,Sedentary Hours Per Day,Income,BMI,Triglycerides,Physical Activity Days Per Week,Sleep Hours Per Day,Country,Continent,Hemisphere,Heart Attack Risk
0,BMW7812,67,Male,208,158/88,72,0,0,1,0,0,4.168189,Average,0,0,9,6.615001,261404,31.251233,286,0,6,Argentina,South America,Southern Hemisphere,0
1,CZE1114,21,Male,389,165/93,98,1,1,1,1,1,1.813242,Unhealthy,1,0,1,4.963459,285768,27.194973,235,1,7,Canada,North America,Northern Hemisphere,0
2,BNI9906,21,Female,324,174/99,72,1,0,0,0,0,2.078353,Healthy,1,1,9,9.463426,235282,28.176571,587,4,4,France,Europe,Northern Hemisphere,0
3,JLN3497,84,Male,383,163/100,73,1,1,1,0,1,9.828130,Average,1,0,9,7.648981,125640,36.464704,378,3,4,Canada,North America,Northern Hemisphere,0
4,GFO8847,66,Male,318,91/88,93,1,1,1,1,0,5.804299,Unhealthy,1,0,6,1.514821,160555,21.809144,231,1,5,Thailand,Asia,Northern Hemisphere,0

In [11]:
df = dados.copy()
df[['Systolic Pressure','Asystolic Pressure']] = dados['Blood Pressure'].str.split('/', expand=True).astype(int)
df = df.drop('Blood Pressure', axis=1)
df.head(10)

,Patient ID,Age,Sex,Cholesterol,Heart Rate,Diabetes,Family History,Smoking,Obesity,Alcohol Consumption,Exercise Hours Per Week,Diet,Previous Heart Problems,Medication Use,Stress Level,Sedentary Hours Per Day,Income,BMI,Triglycerides,Physical Activity Days Per Week,Sleep Hours Per Day,Country,Continent,Hemisphere,Heart Attack Risk,Systolic Pressure,Asystolic Pressure
0,BMW7812,67,Male,208,72,0,0,1,0,0,4.168189,Average,0,0,9,6.615001,261404,31.251233,286,0,6,Argentina,South America,Southern Hemisphere,0,158,88
1,CZE1114,21,Male,389,98,1,1,1,1,1,1.813242,Unhealthy,1,0,1,4.963459,285768,27.194973,235,1,7,Canada,North America,Northern Hemisphere,0,165,93
2,BNI9906,21,Female,324,72,1,0,0,0,0,2.078353,Healthy,1,1,9,9.463426,235282,28.176571,587,4,4,France,Europe,Northern Hemisphere,0,174,99
3,JLN3497,84,Male,383,73,1,1,1,0,1,9.828130,Average,1,0,9,7.648981,125640,36.464704,378,3,4,Canada,North America,Northern Hemisphere,0,163,100
4,GFO8847,66,Male,318,93,1,1,1,1,0,5.804299,Unhealthy,1,0,6,1.514821,160555,21.809144,231,1,5,Thailand,Asia,Northern Hemisphere,0,91,88
5,ZOO7941,54,Female,297,48,1,1,1,0,1,0.625008,Unhealthy,1,1,2,7.798752,241339,20.146840,795,5,10,Germany,Europe,Northern Hemisphere,1,172,86
6,WYV0966,90,Male,358,84,0,0,1,0,1,4.098177,Healthy,0,0,7,0.627356,190450,28.885811,284,4,10,Canada,North America,Northern Hemisphere,1,102,73
7,XXM0972,84,Male,220,107,0,0,1,1,1,3.427929,Average,0,1,4,10.543780,122093,22.221862,370,6,7,Japan,Asia,Northern Hemisphere,1,131,68
8,XCQ5937,20,Male,145,68,1,0,1,1,0,16.868302,Average,0,0,5,11.348787,25086,35.809901,790,7,4,Brazil,South America,Southern Hemisphere,0,144,105
9,FTJ5456,43,Female,248,55,0,1,1,1,1,0.194515,Unhealthy,0,0,4,4.055115,209703,22.558917,232,7,7,Japan,Asia,Northern Hemisphere,0,160,70

In [12]:
diet_map = {
    'Average':   0.5,
    'Unhealthy': 0,
    'Healthy':   1
}


df['Diet'] = dados['Diet'].replace(diet_map).astype(float)

sex_map = {
    'Male':   0,
    'Female': 1,
}

df['Sex'] = dados['Sex'].replace(sex_map).astype(int)

df.head(10)
df.to_csv('colunas_ajustadas.csv', index=False)

C:\Users\thiag\AppData\Local\Temp\ipykernel_11216\4267156257.py:8: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Diet'] = dados['Diet'].replace(diet_map).astype(float)
C:\Users\thiag\AppData\Local\Temp\ipykernel_11216\4267156257.py:15: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Sex'] = dados['Sex'].replace(sex_map).astype(int)

In [19]:
import pandas as pd
from sklearn.cluster import KMeans
import os

# Carregando dataset
caminho_arquivo = 'dados_normalizados.csv'
df = pd.read_csv(caminho_arquivo)
df = df.drop(['Patient ID','Country','Continent','Hemisphere'], axis=1)

# Escolhendo o número de clusters
n_clusters = 3

# Aplicando K-means
kmeans = KMeans(n_clusters=n_clusters, random_state=42)
kmeans.fit(df)

# Adicionando os rótulos dos clusters ao DataFrame
df['Cluster'] = kmeans.labels_

# Criando diretório para salvar os arquivos CSV (se não existir)
output_dir = 'clusters_output'
os.makedirs(output_dir, exist_ok=True)

# Salvando cada cluster em um arquivo CSV
for cluster_num in range(n_clusters):
    cluster_data = df[df['Cluster'] == cluster_num]
    filename = f'cluster_{cluster_num}.csv'
    filepath = os.path.join(output_dir, filename)
    cluster_data.to_csv(filepath, index=False)

print(f"Arquivos CSV salvos na pasta '{output_dir}'")

KeyError: 'Cluster'